// utils/auth/codes.ts (or wherever you keep these)
export const CODES = {
  VALIDATION: "VALIDATION",
  INVALID_ACTION: "INVALID_ACTION",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_CONFIRMED: "EMAIL_NOT_CONFIRMED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  RATE_LIMITED: "RATE_LIMITED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  SUPABASE_SIGNUP_ERROR: "SUPABASE_SIGNUP_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  // success codes
  SIGNUP_VERIFY_EMAIL_SENT: "SIGNUP_VERIFY_EMAIL_SENT",
  SIGNIN_OK: "SIGNIN_OK",
  // ↓ forgot/reset flow
  PASSWORD_RESET_SENT: "PASSWORD_RESET_SENT",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
} as const;

export type ApiCode = (typeof CODES)[keyof typeof CODES];

export const STATUS: Record<ApiCode, number> = {
  [CODES.VALIDATION]: 400,
  [CODES.INVALID_ACTION]: 400,
  [CODES.INVALID_CREDENTIALS]: 401,
  [CODES.EMAIL_NOT_CONFIRMED]: 403,
  [CODES.EMAIL_ALREADY_REGISTERED]: 409,
  [CODES.RATE_LIMITED]: 429,
  [CODES.UNSUPPORTED_MEDIA_TYPE]: 415,
  [CODES.SUPABASE_SIGNUP_ERROR]: 400,
  [CODES.UNEXPECTED_ERROR]: 500,

  [CODES.SIGNUP_VERIFY_EMAIL_SENT]: 200,
  [CODES.SIGNIN_OK]: 200,

  [CODES.PASSWORD_RESET_SENT]: 200,
  [CODES.PASSWORD_RESET_FAILED]: 400,
};
